schema_version: 1

context:
  version: "0.18.0"

package:
  name: oac
  version: ${{ version }}

source:
  url: https://github.com/dlr-pa/oac/archive/v${{ version }}.tar.gz
  sha256: 2f3a142d3fca0e0f38aae91340af0789fe4352f5b411e45127034075d8b4b587

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - oac-run = openairclim.__main__:main
      - oac-gui = openairclim.gui.__main__:main
      - oac-download-data = openairclim.repository:main
      - oac-download-zenodo = openairclim.utils.download_zenodo:main
      - oac-create-artificial-inventories = openairclim.utils.create_artificial_inventories:main
      - oac-create-time-evolution = openairclim.utils.create_time_evolution:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}
    - ambiance
    - cf-units
    - deepmerge
    - joblib
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - pandas <3
    - pint
    - platformdirs
    - pydantic
    - requests
    - scipy
    - toml
    - xarray

tests:
  - python:
      imports:
        - openairclim
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - oac-run --help
      - oac-gui --help
      - oac-download-data --help
      - oac-download-zenodo --help
      - oac-create-artificial-inventories --help
      - oac-create-time-evolution --help

about:
  summary: OpenAirClim is a model for simplified evaluation of the approximate chemistry-climate impact of air traffic emissions.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/dlr-pa/oac

extra:
  recipe-maintainers:
    - ocefpaf
